// WINMAP(_Type,_Name)

#ifndef WINMAP
#error "WINMAP must be defined!"
#endif

WINMAP(RenderWindow, "renderer")
WINMAP(GeometryWindow, "geometry")
WINMAP(ShaderEditor, "shader")
WINMAP(UniformWindow<CgDataType::UniformFloat>, "uniform-float")
WINMAP(UniformWindow<CgDataType::UniformVec2>, "uniform-vec2")
WINMAP(UniformWindow<CgDataType::UniformVec3>, "uniform-vec3")
WINMAP(UniformWindow<CgDataType::UniformVec4>, "uniform-vec4")
WINMAP(UniformWindow<CgDataType::UniformMat3>, "uniform-mat3")
WINMAP(UniformWindow<CgDataType::UniformMat4>, "uniform-mat4")
WINMAP(ColorWindow, "uniform-color")
WINMAP(TimerWindow, "timer")
WINMAP(ArithmeticWindow<CgDataType::UniformFloat>, "arithmetic-float")
WINMAP(ArithmeticWindow<CgDataType::UniformVec2>, "arithmetic-vec2")
WINMAP(ArithmeticWindow<CgDataType::UniformVec3>,"arithmetic-vec3")
WINMAP(ArithmeticWindow<CgDataType::UniformVec4>,"arithmetic-vec4")
WINMAP(BufferWindow<CgDataType::UniformFloat>,"buffer-float")
WINMAP(BufferWindow<CgDataType::UniformVec2>,"buffer-vec2")
WINMAP(BufferWindow<CgDataType::UniformVec3>,"buffer-vec3")
WINMAP(BufferWindow<CgDataType::UniformVec4>,"buffer-vec4")
WINMAP(NoteWindow,"note")
WINMAP(GraphWindow,"graph")
WINMAP(VectorSplitter,"vector-splitter")
WINMAP(VectorMerger,"vector-merger")
WINMAP(ImageSource,"image")
WINMAP(Trigger,"trigger")
WINMAP(ImageBuffer,"image-buffer")
WINMAP(MatrixMult, "matrix-mult")
WINMAP(MatrixTranslate, "matrix-translate")
WINMAP(MatrixRotate, "matrix-rotate")
WINMAP(MatrixScale, "matrix-scale")
WINMAP(MatrixLookAt, "matrix-lookat")
WINMAP(MatrixPerspective, "matrix-perspective")
